version: '3.8'

services:
  postgres:
    container_name: microservice_db
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready --username=postgres"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s  
    ports:
      - 5432:5432
    volumes:
      - ./SQL/create_schema.sql:/docker-entrypoint-initdb.d/init.sql
      
  web:
    container_name: java_microservice
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://microservice_db:5432/microservice?currentSchema=dev
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - 8080:8080
    depends_on:
      postgres:
        condition: service_healthy