version: '3.8'

services:
  postgres:
    container_name: microservice_db
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_DB: microservice
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d microservice"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 120s  
    ports:
      - 5432:5432
    volumes:
      - ./SQL/create_schema.sql:/docker-entrypoint-initdb.d/init.sql
      
  web:
    container_name: java_microservice
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://microservice_db:5432/microservice?currentSchema=dev
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - postgres
      
  minio:
    container_name: minio
    image: quay.io/minio/minio:RELEASE.2023-12-07T04-16-00Z.fips
    command: server /data --console-address ":9001"
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - c:/temp/minio/data:/data
    environment:
      - "MINIO_ROOT_USER=admin"
      - "MINIO_ROOT_PASSWORD=password"
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5

  createbuckets:
    container_name: mc
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 admin password;
      /usr/bin/mc mb myminio/postimages;
      /usr/bin/mc anonymous set public myminio/postimages;
      /usr/bin/mc share download --recursive myminio/postimages
      exit 0;
      "
