apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    app: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: db
          image: postgres:14.1-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: microservice
            - name: POSTGRES_SCHEMA
              value: microservice
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
          volumeMounts:
            - name: pgdata
              mountPath: /docker-entrypoint-initdb.d/create_schema.sql
      volumes:
        - name: pgdata
          hostPath:
            path: /home/docker/create_schema.sql
            type: File


---

apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  selector:
    app: db