server:
  error:
    include-message: always
spring:
  jpa:
    show-sql: true
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
    initialization-mode: always
    url: jdbc:postgresql://localhost:5432/microservice?currentSchema=dev
    username: postgres
    password: postgres
  liquibase:
    liquibase-schema: dev
