server:
  error:
    include-message: always
spring:
  servlet:
    multipart:
      location: c:/temp/servlet_temp_folder
      enabled: true
  jpa:
    show-sql: true
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
    initialization-mode: always
    url: jdbc:postgresql://localhost:5432/microservice?currentSchema=dev
    username: postgres
    password: postgres
#  liquibase:
#    liquibase-schema: dev
logging:
  file: my-app.log
  level:
    org:
      springframework: INFO
  pattern:
    console: d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
minio:
  endpoint: http://localhost:9000
  accessKey: mEHwckpLcE3mihAcJKjI
  secretKey: xtER9wtteKAyx0SNv6HEVX4cN4hZ4jnR6DgIw19i
  bucketName: test