apiVersion: networking.k8s.io/v1
kind: Ingress
metadata: 
  name: {{ .Values.app_name }}-ingress
  namespace: default
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.web_service }}-service
            port:
              number: {{ .Values.app_port }}
