version: '3.8'

services:
  postgres:
    container_name: microservice_db
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - ./create_schema.sql:/docker-entrypoint-initdb.d/init.sql